spring:
  application:
    name: dispatch-manager-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-0x5bg1uy1egiz4y0.us.auth0.com/
          scope:
            - email

  kafka:
    producer:
      acks: 1
      bootstrap-servers:
      - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8091/eureka

property:
  config:
    kafka: 
      dispatch-energy-group-id: dispatch-command-readers
      dispatch-energy-topic: ENERGY_DISPATCH_COMMANDS
      dispatch-energy-partition-count: 1

      replica-count: 1