spring:
  application:
    name: envoy-manager-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-0x5bg1uy1egiz4y0.us.auth0.com/
          scope:
            - email
      
      client:
        registration:
          auth0:
            client-id: 
            client-secret: 
            authorization-grant-type: client_credentials

        provider:
          auth0:
            token-uri: https://dev-0x5bg1uy1egiz4y0.us.auth0.com/oauth/token
            issuer-uri: https://dev-0x5bg1uy1egiz4y0.us.auth0.com/

  datasource:
    url: jdbc:mysql://localhost:3306/envoy_service
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      acks: 1
      bootstrap-servers:
      - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  

    consumer:
      bootstrap-servers:
      - localhost:9092
      group-id: raw-energy-readers
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

    properties:
      # Accept only if headers available from kafka producer
      spring.json.use.type.headers: true
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      # Ensure the package is trusted
      spring.json.trusted.packages: "com.project.hems.*"
      # External defining package mapping 
      spring.json.type.mapping: >
        com.project.hems.dispatch_manager_service.model.DispatchEvent:com.project.hems.envoy_manager_service.model.dispatch.DispatchEvent,
        com.project.hems.simulator_service.model.MeterSnapshot:com.project.hems.envoy_manager_service.model.simulator.MeterSnapshot,
        com.project.hems.SiteManagerService.dto.SiteCreationEvent:com.project.hems.envoy_manager_service.model.site.SiteCreationEvent

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8091/eureka

server:
  port: 8083

property:
  config:
    security:
      oauth2:
        auth0:
          audience: https://api.mfa01.com
          registration_id: auth0
    meter-history:
      batch_size: 60
    kafka: 
      raw-energy-group-id: raw-energy-readers
      raw-energy-topic: RAW_ENERGY_READINGS
      raw-energy-partition-count: 3

      dispatch-energy-group-id: dispatch-command-readers
      dispatch-energy-topic: ENERGY_DISPATCH_COMMANDS
      dispatch-energy-partition-count: 1

      site-creation-group-id: site-creation-readers
      site-creation-topic: SITE_CREATION_DETAILS
      site-creation-partition-count: 1

      replica-count: 1

logging:
  level:
    '[com.project.hems.envoy_manager_service]': debug