spring:

  application:
    name: simulator-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-0x5bg1uy1egiz4y0.us.auth0.com/
          scope:
            - email

  datasource:
    url: jdbc:mysql://localhost:3306/simulator_service
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      acks: 1
      bootstrap-servers:
      - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8091/eureka

server:
  port: 9010

property:
  config:
    kafka: 
      raw-energy-group-id: raw-energy-readers
      raw-energy-topic: RAW_ENERGY_READINGS
      raw-energy-partition-count: 3

      replica-count: 1
